//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderToRestaurant.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant_Storage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurant_Storage()
        {
            this.Menu = new HashSet<Menu>();
            this.Menu1 = new HashSet<Menu>();
            this.Menu2 = new HashSet<Menu>();
        }
    
        public int Ingredient_Code { get; set; }
        public string Ingredient_Name { get; set; }
        public System.DateTime Date_of_Issue { get; set; }
        public string Amount { get; set; }
        public string Shelf_Life { get; set; }
        public int Cost { get; set; }
        public string Supplier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menu2 { get; set; }
    }
}
