//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderToRestaurant.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant_Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurant_Employees()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int Employee_code { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public string Passport { get; set; }
        public int Post_Code { get; set; }
    
        public virtual Restaurant_Posts Restaurant_Posts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
